pipelines:
  branches:
    dev:
      - step:
          name: Deploy Dev Branch to WP Engine Dev
          script:
          - pipe: wpengine/wpe-site-deploy:v1
            variables:
              WPE_SSHG_KEY_PRIVATE: $WPE_SSHG_KEY_PRIVATE
              WPE_ENV: smcazdev
